### ISSUE TITLE
0.1.6 discards options after the first 10 given

### ISSUE THREAD

**Issue by m-dango** [Leont/getopt-long6#10]
When using `Getopt::Long:ver<0.1.6>`, given options are cut off if you provide more than 10.
Using Rakudo 2020.09.

```
$ raku -e 'use Getopt::Long:ver<0.1.6>; get-options.say' {a..z}
\("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")

$ raku -e 'use Getopt::Long:ver<0.1.5>; get-options.say' {a..z}
\("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z")
```

**Comment by Leont** [comment]
Thanks for the clear report. I just release 0.1.7, which fixes this issue.

**Comment by tbrowder** [comment]
On Sun, Oct 25, 2020 at 07:49 Leon Timmermans <notifications@github.com>
wrote:

> Thanks for the clear report. I just release 0.1.7, which fixes this issue.
>
Is there any reason for not taking JMerelo's PR?
