### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by shlomif** [Leont/getopt-long6#2]
See https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ.mdwn#i-want-to-release-my-code---which-open-source-licence-should-i-use . This [script](https://github.com/shlomif/shlomif-computer-settings/blob/master/shlomif-settings/home-bin-executables/bin/find-git-repositories-without-README) may prove of interest as well .

**Comment by Leont** [comment]
Fixed :-)
