### ISSUE TITLE
need a bit of help with usage in the README

### ISSUE THREAD

**Issue by tbrowder** [Leont/getopt-long6#6]
I love this module, **thank you very much!** I used the Perl and GNU C versions heavily during my working years and I'm glad to have it for Raku.

But how to use it is a little vague for those us not being real familiar with Capture classes.  From what I have been able to see from my own examples and debugging, it looks as if when creating any of the forms of 'get-options' the returned Capture will always have .hash elements and no .list elements.

So I see that I always need to do something like this in my code:

    my $capture = get-options(...);
    my %opts = $capture.hash;
    # investigate and handle the options
    for %opts.kv -> $k, $v {
        say "option $k = $v" if $debug;
        if $k eq 'some-option' {
            handle-some-option($v);
        }
    }

If I am correctly interpreting usage, it would be very helpful to mention it early in the README.

**Comment by Leont** [comment]
Yeah that could be documented clearer.

The hash elements will be the named arguments, and the list members will be the positional arguments. E.g. in `foo --bar=2 file` the `.hash` will be `:bar(2)`, and the `.list` will be `file`

**Comment by tbrowder** [comment]
Okay, that helps. So it looks as if all the unknown args will be in the .list if I use the :permute arg to get-options. It seems to me that :permute should be the default to clearly separate desired options from other unknown args for the usual case IMHO. I usually want to warn the user about any unknown args.

Am I wrong?

**Comment by Leont** [comment]
> So it looks as if all the unknown args will be in the .list if I use the :permute arg to get-options.

I'm not sure what you're talking about. Can you give an example?

> It seems to me that :permute should be the default to clearly separate desired options from other unknown args for the usual case

No. Permute is about the ordering of arguments, not the validity.

**Comment by tbrowder** [comment]
>
> I'm not sure what you're talking about. Can you give an example?
>
Yes, I will do so soon.

**Comment by tbrowder** [comment]
An example is in this gist:

  https://gist.github.com/tbrowder/666f7123224b010fd8f6ecc093c63fc3

**Comment by Leont** [comment]
That doesn't tell me what you think is broken about not using `:permute`

**Comment by tbrowder** [comment]
If I don't use  :permute, then unknown args in the middle of the  @*ARGS named elements pollute the other, valid args (args I defined to Getopt::Long). As the developer of the program I want to have all my defined args in the .hash, not accidentally in the .list because the user accidentally put an unrecognized word in the middle of the named args.

**UPDATE**
I guess I don't know what I'm talking about. As I test more I see I don't understand it much at all. But still working on it. Sorry for the noise.

**Comment by tbrowder** [comment]
I think I understand a bit better. From my experiments and reading more about Captures I have come to the following conclusions:

+ to see everything in the Capture use the .pairs method

+ since the Capture is a Seq elements disappear after being observed, so they need to be saved in a new container (I use a hash) obtained by iterating over the .pairs before further manipulation

I intend to create a wrapper module for Getopt::Long to incorporate my use case and greatly ease CLI programming in my style.
